import type { Task } from '@/lib/types';

export const tasks: Task[] = [
  // Submission
  {
    id: '1',
    title: 'ACORD 125 – Commercial Insurance Application',
    description: 'Complete the ACORD 125 form for commercial insurance application.',
    status: 'manual',
    category: 'Submission',
  },
  {
    id: '2',
    title: 'ACORD 130 – Request payroll by classification',
    description: 'Request payroll details by classification using the ACORD 130 form.',
    status: 'manual',
    category: 'Submission',
  },
  {
    id: '3',
    title: 'ACORD 130 – Request employee count & job descriptions',
    description: 'Request employee count and job descriptions via the ACORD 130 form.',
    status: 'manual',
    category: 'Submission',
  },
  {
    id: '4',
    title: 'ACORD 130 – Request loss runs (3–5 years)',
    description: 'Request 3 to 5 years of loss runs using the ACORD 130 form.',
    status: 'manual',
    category: 'Submission',
  },
  {
    id: '5',
    title: 'Research public info (OSHA data, company site)',
    description: 'Research public information including OSHA data and the company website.',
    status: 'ai',
    category: 'Submission',
  },
  {
    id: '6',
    title: 'Write narrative',
    description: 'Compose a narrative based on the gathered information.',
    status: 'ai',
    category: 'Submission',
  },
  {
    id: '7',
    title: 'Generate coverage suggestions',
    description: 'Generate suggestions for insurance coverage.',
    status: 'ai',
    category: 'Submission',
  },
  {
    id: '8',
    title: 'Finalize and approve submission package',
    description: 'Finalize and approve the complete submission package.',
    status: 'manual',
    category: 'Submission',
  },
  // Marketing
  {
    id: '9',
    title: 'Identify suitable carriers for WC',
    description: 'Identify suitable carriers for Workers\' Compensation.',
    status: 'manual',
    category: 'Marketing',
  },
  {
    id: '10',
    title: 'Draft custom marketing emails',
    description: 'Draft custom marketing emails to send to carriers.',
    status: 'ai',
    category: 'Marketing',
  },
  {
    id: '11',
    title: 'Send submission packets',
    description: 'Send out the submission packets to the identified carriers.',
    status: 'ai',
    category: 'Marketing',
  },
  {
    id: '12',
    title: 'Follow up for confirmation',
    description: 'Follow up with carriers for confirmation of receipt.',
    status: 'ai',
    category: 'Marketing',
  },
  {
    id: '13',
    title: 'Review flagged underwriter questions',
    description: 'Review any questions flagged by the underwriters.',
    status: 'ai',
    category: 'Marketing',
  },
  {
    id: '14',
    title: 'Log submissions',
    description: 'Log all sent submissions for tracking purposes.',
    status: 'ai',
    category: 'Marketing',
  },
  {
    id: '15',
    title: 'Track responses & follow-ups',
    description: 'Track all responses and necessary follow-ups from carriers.',
    status: 'ai',
    category: 'Marketing',
  },
  // Proposal
  {
    id: '16',
    title: 'Ingest quotes',
    description: 'Ingest and process quotes received from carriers.',
    status: 'ai',
    category: 'Proposal',
  },
  {
    id: '17',
    title: 'Compare rates, mods, endorsements',
    description: 'Compare rates, modifications, and endorsements from different quotes.',
    status: 'ai',
    category: 'Proposal',
  },
  {
    id: '18',
    title: 'Highlight discrepancies',
    description: 'Highlight any discrepancies found during the comparison.',
    status: 'ai',
    category: 'Proposal',
  },
  {
    id: '19',
    title: 'Generate comparison sheet',
    description: 'Generate a comprehensive comparison sheet of the quotes.',
    status: 'ai',
    category: 'Proposal',
  },
  {
    id: '20',
    title: 'Draft client recommendation',
    description: 'Draft a recommendation for the client based on the analysis.',
    status: 'ai',
    category: 'Proposal',
  },
  {
    id: '21',
    title: 'ACORD 130 – Include loss forecast',
    description: 'Include a loss forecast in the ACORD 130 form.',
    status: 'ai',
    category: 'Proposal',
  },
  {
    id: '22',
    title: 'Package proposal in branded format',
    description: 'Package the final proposal in the company\'s branded format.',
    status: 'ai',
    category: 'Proposal',
  },
  {
    id: '23',
    title: 'Present and discuss',
    description: 'Present the proposal to the client and discuss the details.',
    status: 'manual',
    category: 'Proposal',
  },
  // Binding
  {
    id: '24',
    title: 'Obtain binding confirmation',
    description: 'Obtain the binding confirmation from the carrier.',
    status: 'manual',
    category: 'Binding',
  },
  {
    id: '25',
    title: 'Notify underwriter',
    description: 'Notify the underwriter about the binding decision.',
    status: 'manual',
    category: 'Binding',
  },
  {
    id: '26',
    title: 'Generate COI',
    description: 'Generate the Certificate of Insurance.',
    status: 'ai',
    category: 'Binding',
  },
  {
    id: '27',
    title: 'Generate invoice',
    description: 'Generate the invoice for the client.',
    status: 'ai',
    category: 'Binding',
  },
  {
    id: '28',
    title: 'Send binder/invoice/COI',
    description: 'Send the binder, invoice, and COI to the client.',
    status: 'ai',
    category: 'Binding',
  },
  {
    id: '29',
    title: 'Archive docs',
    description: 'Archive all relevant documents.',
    status: 'ai',
    category: 'Binding',
  },
  // Policy Check-In
  {
    id: '30',
    title: 'Compare issued policy vs binder',
    description: 'Compare the issued policy against the binder.',
    status: 'ai',
    category: 'Policy Check-In',
  },
  {
    id: '31',
    title: 'Flag differences',
    description: 'Flag any differences found between the policy and binder.',
    status: 'ai',
    category: 'Policy Check-In',
  },
  {
    id: '32',
    title: 'Resolve discrepancies',
    description: 'Resolve any discrepancies with the carrier.',
    status: 'manual',
    category: 'Policy Check-In',
  },
  {
    id: '33',
    title: 'Send final policy',
    description: 'Send the final policy to the client.',
    status: 'ai',
    category: 'Policy Check-In',
  },
  {
    id: '34',
    title: 'Archive policy',
    description: 'Archive the final policy document.',
    status: 'ai',
    category: 'Policy Check-In',
  },
];
