import type { Task } from '@/lib/types';

export const tasks: Task[] = [
  { id: 1, phase: 'Submission', taskName: 'ACORD 125 – Commercial Insurance Application', tag: 'manual', status: 'Upcoming', description: 'Task description', subtasks: [{id: 1, text: 'Fill out applicant information'}, {id: 2, text: 'Complete prior carrier information'}] },
  { id: 2, phase: 'Submission', taskName: 'ACORD 130 – Request payroll by classification', tag: 'manual', status: 'Upcoming', description: 'Task description' },
  { id: 3, phase: 'Submission', taskName: 'ACORD 130 – Request employee count & job descriptions', tag: 'manual', status: 'Upcoming', description: 'Task description' },
  { id: 4, phase: 'Submission', taskName: 'ACORD 130 – Request loss runs (3–5 years)', tag: 'manual', status: 'Upcoming', description: 'Task description' },
  { id: 5, phase: 'Submission', taskName: 'Research public info (OSHA data, company site)', tag: 'ai', status: 'Upcoming', description: 'Task description' },
  { id: 6, phase: 'Submission', taskName: 'Write narrative', tag: 'ai', status: 'Upcoming', description: 'Task description' },
  { id: 7, phase: 'Submission', taskName: 'Generate coverage suggestions', tag: 'ai', status: 'Upcoming', description: 'Task description' },
  { id: 8, phase: 'Submission', taskName: 'Finalize and approve submission package', tag: 'manual', status: 'Upcoming', description: 'Task description' },
  { id: 9, phase: 'Marketing', taskName: 'Identify suitable carriers for WC', tag: 'manual', status: 'Upcoming', description: 'Task description' },
  { id: 10, phase: 'Marketing', taskName: 'Draft custom marketing emails', tag: 'ai', status: 'Upcoming', description: 'Task description' },
  { id: 11, phase: 'Marketing', taskName: 'Send submission packets', tag: 'ai', status: 'Upcoming', description: 'Task description' },
  { id: 12, phase: 'Marketing', taskName: 'Follow up for confirmation', tag: 'ai', status: 'Upcoming', description: 'Task description' },
  { id: 13, phase: 'Marketing', taskName: 'Review flagged underwriter questions', tag: 'ai', status: 'Upcoming', description: 'Task description' },
  { id: 14, phase: 'Marketing', taskName: 'Log submissions', tag: 'ai', status: 'Upcoming', description: 'Task description' },
  { id: 15, phase: 'Marketing', taskName: 'Track responses & follow-ups', tag: 'ai', status: 'Upcoming', description: 'Task description' },
  { id: 16, phase: 'Proposal', taskName: 'Ingest quotes', tag: 'ai', status: 'Upcoming', description: 'Task description' },
  { id: 17, phase: 'Proposal', taskName: 'Compare rates, mods, endorsements', tag: 'ai', status: 'Upcoming', description: 'Task description' },
  { id: 18, phase: 'Proposal', taskName: 'Highlight discrepancies', tag: 'ai', status: 'Upcoming', description: 'Task description' },
  { id: 19, phase: 'Proposal', taskName: 'Generate comparison sheet', tag: 'ai', status: 'Upcoming', description: 'Task description' },
  { id: 20, phase: 'Proposal', taskName: 'Draft client recommendation', tag: 'ai', status: 'Upcoming', description: 'Task description' },
  { id: 21, phase: 'Proposal', taskName: 'ACORD 130 – Include loss forecast', tag: 'ai', status: 'Upcoming', description: 'Task description' },
  { id: 22, phase: 'Proposal', taskName: 'Package proposal in branded format', tag: 'ai', status: 'Upcoming', description: 'Task description' },
  { id: 23, phase: 'Proposal', taskName: 'Present and discuss', tag: 'manual', status: 'Upcoming', description: 'Task description' },
  { id: 24, phase: 'Binding', taskName: 'Obtain binding confirmation', tag: 'manual', status: 'Upcoming', description: 'Task description' },
  { id: 25, phase: 'Binding', taskName: 'Notify underwriter', tag: 'manual', status: 'Upcoming', description: 'Task description' },
  { id: 26, phase: 'Binding', taskName: 'Generate COI', tag: 'ai', status: 'Upcoming', description: 'Task description' },
  { id: 27, phase: 'Binding', taskName: 'Generate invoice', tag: 'ai', status: 'Upcoming', description: 'Task description' },
  { id: 28, phase: 'Binding', taskName: 'Send binder/invoice/COI', tag: 'ai', status: 'Upcoming', description: 'Task description' },
  { id: 29, phase: 'Binding', taskName: 'Archive docs', tag: 'ai', status: 'Upcoming', description: 'Task description' },
  { id: 30, phase: 'Policy Check-In', taskName: 'Compare issued policy vs binder', tag: 'ai', status: 'Upcoming', description: 'Task description' },
  { id: 31, phase: 'Policy Check-In', taskName: 'Flag differences', tag: 'ai', status: 'Upcoming', description: 'Task description' },
  { id: 32, phase: 'Policy Check-In', taskName: 'Resolve discrepancies', tag: 'manual', status: 'Upcoming', description: 'Task description' },
  { id: 33, phase: 'Policy Check-In', taskName: 'Send final policy', tag: 'ai', status: 'Upcoming', description: 'Task description' },
  { id: 34, phase: 'Policy Check-In', taskName: 'Archive policy', tag: 'ai', status: 'Upcoming', description: 'Task description' },
];
