import type { Task } from '@/lib/types';

export const tasks: Task[] = [
  { id: 1, phase: 'Submission', taskName: 'ACORD 125 – Commercial Insurance Application', tag: 'manual', status: 'Upcoming', description: 'Complete the ACORD 125 form for commercial insurance applications.' },
  { id: 2, phase: 'Submission', taskName: 'ACORD 130 – Request payroll by classification', tag: 'manual', status: 'Upcoming', description: 'Request payroll information by classification using the ACORD 130 form.' },
  { id: 3, phase: 'Submission', taskName: 'ACORD 130 – Request employee count & job descriptions', tag: 'manual', status: 'Upcoming', description: 'Request employee count and job descriptions using the ACORD 130 form.' },
  { id: 4, phase: 'Submission', taskName: 'ACORD 130 – Request loss runs (3–5 years)', tag: 'manual', status: 'Upcoming', description: 'Request loss runs for the past 3–5 years using the ACORD 130 form.' },
  { id: 5, phase: 'Submission', taskName: 'Research public info (OSHA data, company site)', tag: 'ai', status: 'Upcoming', description: 'Use AI to research public information, including OSHA data and the company website.' },
  { id: 6, phase: 'Submission', taskName: 'Write narrative', tag: 'ai', status: 'Upcoming', description: 'Use AI to write a narrative for the submission package.' },
  { id: 7, phase: 'Submission', taskName: 'Generate coverage suggestions', tag: 'ai', status: 'Upcoming', description: 'Use AI to generate coverage suggestions based on the collected information.' },
  { id: 8, phase: 'Submission', taskName: 'Finalize and approve submission package', tag: 'manual', status: 'Upcoming', description: 'Manually finalize and approve the complete submission package.' },
  { id: 9, phase: 'Marketing', taskName: 'Identify suitable carriers for WC', tag: 'manual', status: 'Upcoming', description: 'Manually identify suitable carriers for Workers\' Compensation.' },
  { id: 10, phase: 'Marketing', taskName: 'Draft custom marketing emails', tag: 'ai', status: 'Upcoming', description: 'Use AI to draft custom marketing emails to suitable carriers.' },
  { id: 11, phase: 'Marketing', taskName: 'Send submission packets', tag: 'ai', status: 'Upcoming', description: 'Use AI to send submission packets to the identified carriers.' },
  { id: 12, phase: 'Marketing', taskName: 'Follow up for confirmation', tag: 'ai', status: 'Upcoming', description: 'Use AI to follow up with carriers for confirmation of receipt.' },
  { id: 13, phase: 'Marketing', taskName: 'Review flagged underwriter questions', tag: 'ai', status: 'Upcoming', description: 'Use AI to review and flag questions from underwriters.' },
  { id: 14, phase: 'Marketing', taskName: 'Log submissions', tag: 'ai', status: 'Upcoming', description: 'Use AI to log all sent submissions.' },
  { id: 15, phase: 'Marketing', taskName: 'Track responses & follow-ups', tag: 'ai', status: 'Upcoming', description: 'Use AI to track responses and manage follow-ups with carriers.' },
  { id: 16, phase: 'Proposal', taskName: 'Ingest quotes', tag: 'ai', status: 'Upcoming', description: 'Use AI to ingest and process quotes received from carriers.' },
  { id: 17, phase: 'Proposal', taskName: 'Compare rates, mods, endorsements', tag: 'ai', status: 'Upcoming', description: 'Use AI to compare rates, modifications, and endorsements from different quotes.' },
  { id: 18, phase: 'Proposal', taskName: 'Highlight discrepancies', tag: 'ai', status: 'Upcoming', description: 'Use AI to highlight any discrepancies found during the comparison.' },
  { id: 19, phase: 'Proposal', taskName: 'Generate comparison sheet', tag: 'ai', status: 'Upcoming', description: 'Use AI to generate a comprehensive comparison sheet of all quotes.' },
  { id: 20, phase: 'Proposal', taskName: 'Draft client recommendation', tag: 'ai', status: 'Upcoming', description: 'Use AI to draft a client recommendation based on the comparison.' },
  { id: 21, phase: 'Proposal', taskName: 'ACORD 130 – Include loss forecast', tag: 'ai', status: 'Upcoming', description: 'Use AI to include a loss forecast in the ACORD 130 form.' },
  { id: 22, phase: 'Proposal', taskName: 'Package proposal in branded format', tag: 'ai', status: 'Upcoming', description: 'Use AI to package the proposal in a branded format.' },
  { id: 23, phase: 'Proposal', taskName: 'Present and discuss', tag: 'manual', status: 'Upcoming', description: 'Manually present and discuss the proposal with the client.' },
  { id: 24, phase: 'Binding', taskName: 'Obtain binding confirmation', tag: 'manual', status: 'Upcoming', description: 'Manually obtain binding confirmation from the client.' },
  { id: 25, phase: 'Binding', taskName: 'Notify underwriter', tag: 'manual', status: 'Upcoming', description: 'Manually notify the underwriter of the binding decision.' },
  { id: 26, phase: 'Binding', taskName: 'Generate COI', tag: 'ai', status: 'Upcoming', description: 'Use AI to generate the Certificate of Insurance (COI).' },
  { id: 27, phase: 'Binding', taskName: 'Generate invoice', tag: 'ai', status: 'Upcoming', description: 'Use AI to generate the invoice for the client.' },
  { id: 28, phase: 'Binding', taskName: 'Send binder/invoice/COI', tag: 'ai', status: 'Upcoming', description: 'Use AI to send the binder, invoice, and COI to the client.' },
  { id: 29, phase: 'Binding', taskName: 'Archive docs', tag: 'ai', status: 'Upcoming', description: 'Use AI to archive all relevant documents.' },
  { id: 30, phase: 'Policy Check-In', taskName: 'Compare issued policy vs binder', tag: 'ai', status: 'Upcoming', description: 'Use AI to compare the issued policy with the binder.' },
  { id: 31, phase: 'Policy Check-In', taskName: 'Flag differences', tag: 'ai', status: 'Upcoming', description: 'Use AI to flag any differences between the policy and the binder.' },
  { id: 32, phase: 'Policy Check-In', taskName: 'Resolve discrepancies', tag: 'manual', status: 'Upcoming', description: 'Manually resolve any discrepancies found.' },
  { id: 33, phase: 'Policy Check-In', taskName: 'Send final policy', tag: 'ai', status: 'Upcoming', description: 'Use AI to send the final policy to the client.' },
  { id: 34, phase: 'Policy Check-In', taskName: 'Archive policy', tag: 'ai', status: 'Upcoming', description: 'Use AI to archive the final policy.' },
];
